name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libopenjp2-tools
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build app for Windows
      if: runner.os == 'Windows'
      run: npm run build:win
      
    - name: Build app for macOS
      if: runner.os == 'macOS'
      run: npm run build:mac
      
    - name: Build app for Linux
      if: runner.os == 'Linux'
      run: npm run build:linux
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          dist/
          !dist/**/*.map
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: Display structure of downloaded files
      run: ls -la ./artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        files: |
          ./artifacts/build-windows-latest/dist/*.exe
          ./artifacts/build-windows-latest/dist/*.msi
          ./artifacts/build-macos-latest/dist/*.dmg
          ./artifacts/build-macos-latest/dist/*.zip
          ./artifacts/build-ubuntu-latest/dist/*.AppImage
          ./artifacts/build-ubuntu-latest/dist/*.deb
          ./artifacts/build-ubuntu-latest/dist/*.rpm
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}